# Generated by Django 4.0.5 on 2022-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('trueOption', models.CharField(max_length=100)),
                ('otherOption1', models.CharField(max_length=100)),
                ('otherOption2', models.CharField(max_length=100)),
                ('otherOption3', models.CharField(max_length=100)),
            ],
        ),
    ]
