# Generated by Django 4.0.5 on 2022-07-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_questionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='trueOption',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer',
            field=models.CharField(choices=[('option1', models.CharField(max_length=100)), ('option2', models.CharField(max_length=100)), ('option3', models.CharField(max_length=100)), ('option4', models.CharField(max_length=100, null=True))], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='otherOption4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
