# Generated by Django 4.0.5 on 2022-07-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_questionanswer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='otherOption1',
            new_name='Option1',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='otherOption2',
            new_name='Option2',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='otherOption3',
            new_name='Option3',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='otherOption4',
            new_name='Option4',
        ),
    ]
