# Generated by Django 4.0.5 on 2022-07-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_questionanswer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
    ]
