# Generated by Django 4.0.5 on 2022-07-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_questionanswer_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
