# Generated by Django 4.0.5 on 2022-07-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_questionanswer_remove_choice_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.question'),
        ),
    ]
