# Generated by Django 4.0.5 on 2022-07-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_selectedchoice_alter_choice_selected_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='selected_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.selectedchoice'),
        ),
    ]
