# Generated by Django 4.0.5 on 2022-07-30 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_choice_selected_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedchoice',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='selectedchoice',
            name='selectedChoice_text',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.selectedchoice'),
        ),
    ]
