# Generated by Django 4.0.5 on 2022-07-30 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0022_remove_selectedchoice_selected_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedchoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selectedchoice',
            name='selectedChoice_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
