# Generated by Django 4.0.5 on 2022-07-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_selectedchoice_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='selectedchoice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.question'),
        ),
    ]
