# Generated by Django 4.0.5 on 2022-07-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_choice_selected_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedchoice',
            name='exam',
            field=models.ManyToManyField(to='base.exam'),
        ),
    ]
