# Generated by Django 4.0.5 on 2022-08-14 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0025_selectedchoice_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='user',
        ),
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
