# Generated by Django 4.0.5 on 2022-12-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_exam_score_remove_exam_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='edit_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date edited'),
        ),
        migrations.AddField(
            model_name='exam',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date published'),
        ),
    ]
