# Generated by Django 4.0.5 on 2022-12-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_exam_edit_date_exam_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='edit_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='exam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='exam',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Edited'),
        ),
    ]
