# Generated by Django 4.0.5 on 2022-12-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_exam_edit_date_remove_exam_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='score',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Edited'),
        ),
    ]
